import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"], // Subconjunto de caracteres (latim)
  variable: "--font-instrument-sans", // Variável CSS para a fonte
  display: 'swap', // Garante que a fonte seja exibida imediatamente com fallback
  weight: ["400", "500", "600", "700"], // Especifica os pesos da fonte
  style: ["normal", "italic"], // Especifica os estilos (normal e itálico)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${instrumentSans.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}